<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/*
 @author: Adhiraj Lamichhane
    The model to create the 'categories' table in the database.
    This table is used to store the categories of the application.
    This model is automatically generated by the IVM framework.

    Code Reference:
    https://laravel.com/docs/10.x/eloquent
 */


class Category extends Model
{
    use HasFactory;
    protected $guarded = []; // This is used to prevent mass assignment.
}
