<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
/*

 @author: Diwash Mainali
The model to create the 'products' table in the database.
This table is used to store the products of the application.
This model is automatically generated by the IVM framework.

Code Reference:
https://laravel.com/docs/10.x/eloquent

 */
class InvoiceDetail extends Model
{
    use HasFactory;
    protected $guarded = [];    // This is used to prevent mass assignment.
    public function product(){
        // define the relationship between the invoice detail and the product.
        return $this->belongsTo(Product::class,'product_id','id');
    }


    public function category(){
        // define the relationship between the invoice detail and the category.
        return $this->belongsTo(Category::class,'category_id','id');
    }
}
