<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/*
 @author: Adhiraj Lamichhane
    The model to create the 'invoices' table in the database.
    This table is used to store the invoices of the application.
    This model is automatically generated by the IVM framework.

    Code Reference:
    https://laravel.com/docs/10.x/eloquent
 */
class Invoice extends Model
{
    use HasFactory;
    protected $guarded = []; //prevent mass assignment.
    public function payment(){
        // define the relationship between the invoice and the payment.
        return $this->belongsTo(Payment::class,'id','invoice_id');
    }

    public function invoice_details(){
        // define the relationship between the invoice and the invoice details.
        return $this->hasMany(InvoiceDetail::class,'invoice_id','id');
    }
}
