<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
/*
@author: Adhiraj Lamichhane
    The model to create the 'products' table in the database.
    This table is used to store the products of the application.
    This model is automatically generated by the IVM framework.

    Code Reference:
    https://laravel.com/docs/10.x/eloquent
*/

class Product extends Model
{
    use HasFactory;
    protected $guarded = []; //prevent mass assignment.


    public function supplier(){
        // define the relationship between the product and the supplier.
        return $this->belongsTo(Supplier::class,'supplier_id','id');
    }

    public function unit(){
        // define the relationship between the product and the unit.
        return $this->belongsTo(Unit::class,'unit_id','id');
    }

    public function category(){
        // define the relationship between the product and the category.
        return $this->belongsTo(Category::class,'category_id','id');
    }




}
