<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
/*
@author: Diwash Mainali
The model to create the 'suppliers' table in the database.
This table is used to store the suppliers of the application.
This model is automatically generated by the IVM framework.

Code Reference:
https://laravel.com/docs/10.x/eloquent
*/

class Supplier extends Model
{
    use HasFactory;
    protected $guarded = []; //prevent mass assignment.
}
